version: "3"
services:
  frontend:
    image: lornafay/expense-me:latest
    container_name: react-container
    ports:
      - "3001:3000"
    volumes:
      - react_build:/react/build
    stdin_open: true
    restart: always

volumes:
  react_build: