version: "3"
services:
  frontend:
    image: lornafay/expense-me:latest
    container_name: react-container
    volumes:
      - react_build:/react/build
    stdin_open: true
    restart: always

  nginx:
      image: nginx:latest
      ports:
        - 8080:8080
      volumes:
        - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
        - react_build:/var/www/react
      container_name: nginx-container
      depends_on:
        - frontend

volumes:
  react_build: