apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 30000
  selector:
    app: frontend
