version: "3"
services:
  frontend:
    build:
      context: .
    ports:
        - "3001:3000"
    container_name: react-container
    volumes:
      - react_build:/react/build
    stdin_open: true


volumes:
  react_build: